version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: encryption-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - CACHE_TTL=3600
      - LOG_LEVEL=info
      - ENVIRONMENT=production
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - encryption-network

  redis:
    image: redis:alpine
    container_name: encryption-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - encryption-network

networks:
  encryption-network:
    driver: bridge

volumes:
  redis-data:
    driver: local 